# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JN5vUfEFl4mdBl5-u_DW6Odrf-yIIp_Q
"""

!pip install waitress
!pip install flask_ngrok
!pip install gunicorn

from flask import Flask,  jsonify,request
from math import sqrt
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from pandas import DataFrame
from waitress import serve
from flask import *
from flask_ngrok import run_with_ngrok

import numpy as np
import pandas as pd
import  pickle

app = Flask(__name__)


#import model
dir="/content/drive/MyDrive/ML_Project/dtr_new.sav"
reg = pickle.load( open(dir, 'rb')) #load bac

def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df


'''-----------------------  START RECCOMMEND  ------------------------'''
@app.route('/', methods=['POST','GET'])
def predict():


    if request.method=='POST':

        l=[]
        l.append(request.form.get('meter'))
        l.append(request.form.get('site_id'))
        l.append(request.form.get('primary_use'))
        l.append(request.form.get('square_feet'))
        l.append(request.form.get('air_temperature'))
        l.append(request.form.get('cloud_coverage'))
        l.append(request.form.get('dew_temperature'))
        l.append(request.form.get('precip_depth_1_hr'))
        l.append(request.form.get('sea_level_pressure'))
        l.append(request.form.get('wind_direction'))
        l.append(request.form.get('wind_speed'))
        
        col_name=['meter','site_id','primary_use','square_feet',
          'air_temperature','cloud_coverage', 'dew_temperature',
          'precip_depth_1_hr','sea_level_pressure','wind_direction',
          'wind_speed']

        ___df = DataFrame ([l],columns=col_name)

        di = {"Education": 0, 'Entertainment/public assembly':1,
              'Food sales and service':2,'Healthcare':3 ,'Lodging/residential':4 ,
              'Manufacturing/industrial':5,'Office':6,'Other':7,'Parking':8,
              'Public services':9,'Religious worship':10,'Retail':11,'Services':12,
              'Technology/science':13,'Utility':14,'Warehouse/storage':15}
        df = ___df.replace({"primary_use": di})

        input_user=reduce_mem_usage(df)
        meter_reading = np.expm1(reg.predict(df))

        if ((df['meter'].any()==0) and  (df['site_id'].any()==0)):
            meter_reading=meter_reading*0.2931 
        
        return '''
                <html lang="en">
                <head>
                  <title>ECP</title>
                  <title>Energy Consumption Predictor</title>
                  <meta charset="utf-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
                  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
                  <style>
                    /* Remove the navbar's default margin-bottom and rounded borders */ 
                    
                  </style>
                </head>

                <body style="background:transparent url('http://prod-upp-image-read.ft.com/8cc86046-bc94-11e8-94b2-17176fbf93f5') no-repeat center center /cover">

                <nav class="navbar navbar-inverse">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                      </button>

                      <a class="navbar-brand" href="#">ECP</a>

                    </div>

                  </div>
                </nav>


                <div class="jumbotron">
                   <div class="container text-center">

                    <h1>ECP</h1>
                    <h4>Energy Consumption Predictor</h4>      
                    <h4> Your Energy Consumption is :{} </h4>

                  </div>
                </div>


                <div class="container-fluid bg-3 text-center"> 
                  <div class="row">
                    <div class="col-sm-3">

                    </div>
                    <div class="col-sm-3"> 

                    </div>
                    <div class="col-sm-3"> 

                    </div>
                    <div class="col-sm-3">

                    </div>
                  </div>
                </div>
                <br>



                <div class="container-fluid bg-3 text-center">    
                  <div class="row">
                    <div class="col-sm-3">           

                    </div>
                    <div class="col-sm-3"> 

                    </div>
                    <div class="col-sm-3"> 

                    </div>
                    <div class="col-sm-3">

                    </div>
                  </div>
                </div>
                <br>

                <div class="container-fluid bg-3 text-center">      
                  <div class="row">
                    <div class="col-sm-3">

                    </div>
                    <div class="col-sm-3"> 

                    </div>
                    <div class="col-sm-3"> 

                    </div>
                    <div class="col-sm-3">

                    </div>
                  </div>
                </div><br>

                <div class="container-fluid bg-3 text-center">      

                </div><br>

                <footer class="container-fluid text-center">
                  <p>© 2021 ECP ALL RIGHTS RESERVED</p>
                </footer>       

                </body>
                </html>
                '''.format(meter_reading[0])


    return  '''
            <html lang="en">
            
            <head>
              <title>ECP</title>
              <title>Energy Consumption Predictor</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
              <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
              <style>
                /* Remove the navbar's default margin-bottom and rounded borders */ 
                .navbar {
                  margin-bottom: 0;
                  border-radius: 0;
                }

                /* Add a gray background color and some padding to the footer */
                footer {
                  background-color: #f2f2f2;
                  padding: 25px;
                }
                
                .jumbotron {
                    padding-top: 30px;
                    padding-bottom: 30px;
                    margin-bottom: 30px;
                    color: inherit;
                    background-color: #9f939370;
                }
                
                label {
                display: inline-block;
                max-width: 100%;
                margin-bottom: 5px;
                font-weight: 900;
                background-color: #ffffff75;
                }
                
                
                .btn-primary {
                    color: #fff;
                    font-weight: 900;
                    background-color: #31708f;
                    border-color: #31708f;
                }
                
              </style>
            </head>
            

            
            <body style="background:transparent url('http://prod-upp-image-read.ft.com/8cc86046-bc94-11e8-94b2-17176fbf93f5') no-repeat center center /cover">

            <nav class="navbar navbar-inverse">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>
                  
                  <a class="navbar-brand" href="#">ECP</a>
                  
                </div>

              </div>
            </nav>


            <div class="jumbotron">
               <div class="container text-center">
              
                <h1>ECP</h1>
                <h4>Energy Consumption Predictor</h4>      
                <p> Assessing the value of energy efficiency improvements can be challenging as there's no way to truly know how much energy a building would have used without the improvements. </p>
                <p> Based on historic usage rates and observed weather we can predict the Energy Consumption.</p>
                <p> All you have to do is fill this required data. and press on Predict Button</p>
              </div>
            </div>



            
            <form method="POST">
            <div class="container-fluid bg-3 text-center"> 
              <div class="row">
                <div class="col-sm-3">
                    <label for="Meter">Meter:</label>
                    <input type="text" class="form-control" id="Meter" name="meter">
                </div>
                <div class="col-sm-3"> 
                  <label for="site_id">Site ID:</label>
                  <input type="text" class="form-control" id="site_id" name="site_id">
                </div>
                <div class="col-sm-3"> 
                  <label for="primary_use">Primary Use:</label>
                  <input type="text" class="form-control" id="primary_use" name="primary_use">
                </div>
                <div class="col-sm-3">
                  <label for="square_feet">Square Feet:</label>
                  <input type="text" class="form-control" id="square_feet" name="square_feet">
                </div>
              </div>
            </div>
            <br>
            


            <div class="container-fluid bg-3 text-center">    
              <div class="row">
                <div class="col-sm-3">           
                  <label for="air_temperature">Air Temperature:</label>
                  <input type="text" class="form-control" id="air_temperature" name="air_temperature">
                </div>
                <div class="col-sm-3"> 
                  <label for="cloud_coverage">Cloud Coverage:</label>
                  <input type="text" class="form-control" id="cloud_coverage" name="cloud_coverage">
                </div>
                <div class="col-sm-3"> 
                  <label for="dew_temperature">Dew Temperature:</label>
                  <input type="text" class="form-control" id="dew_temperature" name="dew_temperature">
                </div>
                <div class="col-sm-3">
                  <label for="precip_depth_1_hr">Precip Depth 1 hr:</label>
                  <input type="text" class="form-control" id="precip_depth_1_hr" name="precip_depth_1_hr">
                </div>
              </div>
            </div>
            <br>



            
            <div class="container-fluid bg-3 text-center">      
              <div class="row">
                <div class="col-sm-3">
                      <label for="sea_level_pressure">Sea Level Pressure:</label>
                      <input type="text" class="form-control" id="sea_level_pressure" name="sea_level_pressure">
                </div>
                <div class="col-sm-3"> 
                      <label for="wind_direction">Wind Direction:</label>
                      <input type="text" class="form-control" id="wind_direction" name="wind_direction">
                </div>
                <div class="col-sm-3"> 
                      <label for="wind_speed">Wind Speed:</label>
                      <input type="text" class="form-control" id="wind_speed" name="wind_speed">
                </div>
                <div class="col-sm-3">
                     <label ></label>
                </div>
              </div>
            </div><br>

            
            <div class="container-fluid bg-3 text-center">      
                <button type="submit" class="btn btn-primary">Predict Energy Consumption</button>
            </div><br>

            </form>

            <footer class="container-fluid text-center">
              <p>© 2021 ECP ALL RIGHTS RESERVED</p>
            </footer>       

            </body>
            </html>

            '''

run_with_ngrok(app)
app.run()

!pip freeze > requirements.txt

